- name: Generation MD5
  hosts: all
  gather_facts: false
  tasks:
    - name: Generation MD5 for ssh key
      shell: "ssh-keygen -E md5 -lf .ssh/TestPidor.pub | cut -c 10- | cut -c -47"                #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.htm/l
      register: generation_md5

    - debug:
        msg: "{{ generation_md5.stdout }}"