- name: Update apt repo and cache on Ubuntu VM
  apt:                                                                                              #https://docs.ansible.com/ansible/2.9/modules/apt_module.html
    state: latest                                                                            
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all packages on VM
  apt: 
    upgrade: dist
    force_apt_get: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openvpn
    - easy-rsa
    - mc
    - net-tools

- name: Reboot VM
  reboot: 
    reboot_timeout: 3600
