- name: Delete SSH key
  digital_ocean_sshkey:                                                     #https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_module.html
    state: absent
    fingerprint: "{{ DROPLET_FINGERPRINT }}"
    oauth_token: "{{ DIGITALOCEAN_TOKEN }}"

- name: Delete droplet
  digital_ocean:
    state: deleted
    id: "{{ DROPLET_ID }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"
    region_id: fra1
    size_id: 1gb
    image_id: ubuntu-20-04-x64
    command: droplet
    name: "{{ DROPLET_NAME }}"
    wait_timeout: 500
    unique_name: yes

