- name: Create folder
  file:                                                                                   #https://docs.ansible.com/ansible/2.9/modules/file_module.html
    path: ./.ssh
    state: directory

- name: Generate an OpenSSH rsa keypair with a different size (4096 bits)
  openssh_keypair:                                                                        #https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html
    path: "./.ssh/{{ DROPLET_NAME }}" 
    size: 4096
    mode: '600'

- name: ensure ssh key exists
  user: 
    name: "{{ DROPLET_NAME }}"
    generate_ssh_key: yes
    ssh_key_file: "./.ssh/{{ DROPLET_NAME }}"
    
- name: Ensure a SSH key is present
  community.digitalocean.digital_ocean:                                                     #https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_module.html
    state: present
    command: ssh
    name: "{{ DROPLET_NAME }}"
    ssh_pub_key: "{{ lookup('file', './.ssh/{{ DROPLET_NAME }}.pub') }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"

- name: Generation MD5 for ssh key
  shell: "ssh-keygen -E md5 -lf .ssh/{{ DROPLET_NAME }}.pub | cut -c 10- | cut -c -47"      #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
  register: generation_md5 

- name: Create new droplet Digital Ocean
  digital_ocean:                                                                            #https://docs.ansible.com/ansible/2.9/modules/digital_ocean_module.html
    state: present
    command: droplet
    name: "{{ DROPLET_NAME }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"
    size_id: 1gb
    region_id: fra1
    image_id: ubuntu-20-04-x64
    wait_timeout: 500
    unique_name: yes
    ssh_key_ids: "{{ generation_md5.stdout }}"
  register: my_droplet
  

- debug:
    msg: "ID is {{ my_droplet.droplet.id }}"

- debug:
    msg: "IP is {{ my_droplet.droplet.ip_address }}"

- name: Write ip and id of droplet
  copy:
    dest: "./{{ DROPLET_NAME }}.yml"
    content: |
      "DROPLET_ID: {{ my_droplet.droplet.id }}"
      "IP: {{ my_droplet.droplet.ip_address }}"
      "DROPLET_FINGERPRINT: {{ generation_md5.stdout }}"