- name: Create new droplet Digital Ocean
  community.digitalocean.digital_ocean:
    state: present
    command: droplet
    name: "{{ DROPLET_NAME }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"
    size_id: 1gb
    region_id: fra1
    image_id: ubuntu-20-04-x64
    wait_timeout: 500
    unique_name: yes
  register: my_droplet
  

- debug:
    msg: "ID is {{ my_droplet.droplet.id }}"

- debug:
    msg: "IP is {{ my_droplet.droplet.ip_address }}"

- name: Write ip and id of droplet
  copy:
    dest: "./{{ DROPLET_NAME }}"
    content: |
      "ID is {{ my_droplet.droplet.id }}"
      "IP is {{ my_droplet.droplet.ip_address }}"