- name: Create folder
  file:
    path: ./.ssh
    state: directory

- name: Generate an OpenSSH rsa keypair with a different size (4096 bits)
  openssl_privatekey:                                                                          #https://docs.ansible.com/ansible/2.5/modules/openssl_privatekey_module.html more relaible module
    path: "./.ssh/{{ DROPLET_NAME }}.pem" 
    size: 4096
    mode: '600'
    type: DSA
  register: md5-key

- name: "Getting md5 fingerprint for {{ DROPLET_NAME }}"
  set_fact:
    generation_md5: "{{ item.value }}"
  loop: "{{ lookup('dict', md5-key.fingerprint }}"
  when: "'md5' in item.key"
  
- name: Create new droplet Digital Ocean
  digital_ocean:                                                                            #https://docs.ansible.com/ansible/2.9/modules/digital_ocean_module.html
    state: present
    command: droplet
    name: "{{ DROPLET_NAME }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"
    size_id: 1gb
    region_id: fra1
    image_id: ubuntu-20-04-x64
    wait_timeout: 500
    unique_name: yes
    ssh_key_ids: "{{ generation_md5 }}"
  register: my_droplet
  

- debug:
    msg: "ID is {{ my_droplet.droplet.id }}"

- debug:
    msg: "IP is {{ my_droplet.droplet.ip_address }}"

- name: Write ip and id of droplet
  copy:
    dest: "./{{ DROPLET_NAME }}"
    content: |
      "ID is {{ my_droplet.droplet.id }}"
      "IP is {{ my_droplet.droplet.ip_address }}"