- name: Create folder
  file:
    path: ./.ssh
    state: directory

- name: Generate an OpenSSH rsa keypair with a different size (4096 bits)
  openssh_keypair:
    path: "./.ssh/{{ DROPLET_NAME }}" 
    size: 4096
    mode: '600'
  

- name: Create new droplet Digital Ocean
  community.digitalocean.digital_ocean:
    state: present
    command: droplet
    name: "{{ DROPLET_NAME }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"
    size_id: 1gb
    region_id: fra1
    image_id: ubuntu-20-04-x64
    wait_timeout: 500
    unique_name: yes
    ssh_pub_key: "{{ lookup('file', './.ssh/{{ DROPLET_NAME }}.pub') }}"
  register: my_droplet
  

- debug:
    msg: "ID is {{ my_droplet.droplet.id }}"

- debug:
    msg: "IP is {{ my_droplet.droplet.ip_address }}"

- name: Write ip and id of droplet
  copy:
    dest: "./{{ DROPLET_NAME }}"
    content: |
      "ID is {{ my_droplet.droplet.id }}"
      "IP is {{ my_droplet.droplet.ip_address }}"

- name: Ensure a droplet is present with SSH keys installed
  community.digitalocean.digital_ocean_droplet:
    state: present
    id: " {{ my_droplet.droplet.id }}"
    name: "{{ DROPLET_NAME }}"
    api_token: "{{ DIGITALOCEAN_TOKEN }}"
    size: 1gb
    region: fra1
    ssh_keys: ['', '1784768']
    image: ubuntu-20-04-x64
    wait_timeout: 500