---
# handlers file for node-docker-provision
- name: check_docker
  docker_container:
    name: test_docker
    image: hello-world
    auto_remove: true
  register: output
  notify: Docker output log

- name: Docker output log
  debug:
    msg: "{{ output.container.State }}"