- name: Deleting user
  user:
    name: "{{ USER_NAME }}"
    state: absent

- name: Deleting user home dir
  file:
    path: "/home/{{ USER_NAME }}"
    state: absent

- name: "Deleting old keys on local machine"
  file:
    path: ".ssh/{{ item }}"
    state: absent
  delegate_to: localhost
  loop:
    - "{{ USER_NAME }}_rsa"
    - "{{ USER_NAME }}_rsa.pub"
