---
# tasks file for openvpn

- name: IP Server
  shell: "wget -q -4 -O- http://icanhazip.com"
  register: this

- name: Create Server dirs and links
  file:                                                                         #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    path: "~/{{ item }}"
    state: directory
  loop:
    - "{{ CERT_ROOT_DIR }}"

- name: Get Server template
  template:                                                                     #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
    src: "{{ item.name }}.j2" 
    dest: "{{ item.path }}"
  loop:
    - { name: "server.conf", path: "/etc/openvpn/server.conf" }
    - { name: "client.ovpn", path: "/etc/openvpn/client.ovpn" }
    - { name: "vars", path: "~/{{ CERT_ROOT_DIR }}/vars"}

- name: Build PKI
  command: 
    cmd: /usr/share/easy-rsa/easyrsa init-pki                                 #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: "Build CA"
  become: yes
  shell: >                                                                     #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
    yes "" | /usr/share/easy-rsa/easyrsa build-ca nopass;
  args: 
    chdir: "~/{{ CERT_ROOT_DIR }}"
    executable: /bin/bash

- name: Build DH
  command: "/usr/share/easy-rsa/easyrsa gen-dh"                                #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Build PEM key
  command: "/usr/share/easy-rsa/easyrsa gen-crl"
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Build TA
  command: "openvpn --genkey --secret ta.key"                                 #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Build certificate server
  command: "/usr/share/easy-rsa/easyrsa build-server-full server nopass"      #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Copy server.key, server.crt, ca.crt, dh.pem, ta.key
  copy:                                                                       #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    src: "~/{{ CERT_ROOT_DIR }}/{{ item.path }}/{{ item.name }}"
    dest: "/etc/openvpn/{{ item.name }}"
    remote_src: yes  
  loop:
    - { name: "server.crt", path: "pki/issued"}
    - { name: "server.key", path: "pki/private"}
    - { name: "ca.crt", path: "pki"}
    - { name: "crl.pem", path: "pki"}
    - { name: "dh.pem", path: "pki"}
    - { name: "ta.key", path: "."}

- name: Changing Permissions to file server.key
  ansible.builtin.file:
    path: "/etc/openvpn/server.key"
    mode: '0600'
    remote_src: yes

- name: Changing Permissions to file ta.key
  ansible.builtin.file:
    path: "/etc/openvpn/ta.key"
    mode: '0600'
    remote_src: yes

#- name: Forward network packages
#  shell: sysctl -w net.ipv4.ip_forward=1                                    #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html

- name: Configuration IP forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Allow OpenSSH rule
  ufw:                                                                        #https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
    rule: allow
    name: OpenSSH

- name: Allow OpenVPN rule
  ufw:                                                                        #https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
    rule: allow
    port: openvpn
    comment: "OpenVPN"

- name: Allow everything and enable UFW
  ufw:                                                                        #https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
    state: enabled
    policy: allow

- name: Added rules Firewall                                                  #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html       
  shell: iptables -I FORWARD -i tun0 -o eth0 -j ACCEPT &&                    
          iptables -I FORWARD -i eth0 -o tun0 -j ACCEPT &&
          iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

- name: Reloaded systemd / Restarted OpenVPN service
  systemd:                                                                    #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
    daemon_reload: yes
    name: openvpn 
    state: restarted

- name: Reloaded systemd
  systemd:                                                                    #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
    name: openvpn 
    state: started
    enabled: yes


######### Client 

- name: Create USERNAME_DIR                                             #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
  shell: mkdir $(whoami)
  args:
    chdir: "/etc/openvpn/client/"
    warn: false

- name: Whoami                                            #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
  shell: whoami
  register: USERNAME

- name: Build certificate client
  shell: /usr/share/easy-rsa/easyrsa build-client-full $(whoami) nopass && 
          cp -r ~/{{ CERT_ROOT_DIR }}/pki/issued/$(whoami).crt /etc/openvpn/client/$(whoami) &&
          cp -r ~/{{ CERT_ROOT_DIR }}/pki/private/$(whoami).key /etc/openvpn/client/$(whoami)    #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
  args:
    chdir: "{{ CERT_ROOT_DIR }}"


- name: "Create client ovpn file"
  become: yes
  shell: "{{ item }}"
  with_items:
    - echo -e '<ca>' >> /etc/openvpn/client.ovpn
    - cat /etc/openvpn/ca.crt >> /etc/openvpn/client.ovpn
    - echo -e '</ca>\n<cert>' >> /etc/openvpn/client.ovpn
    - cat /etc/openvpn/client/$(whoami)/$(whoami).crt >> /etc/openvpn/client.ovpn
    - echo -e '</cert>\n<key>' >> /etc/openvpn/client.ovpn
    - cat /etc/openvpn/client/$(whoami)/$(whoami).key >> /etc/openvpn/client.ovpn
    - echo -e '</key>\n<tls-crypt>' >> /etc/openvpn/client.ovpn
    - cat /etc/openvpn/ta.key >> /etc/openvpn/client.ovpn
    - echo -e '</tls-crypt>' >> /etc/openvpn/client.ovpn
  args:
    chdir: "/etc/openvpn/"
    executable: /bin/bash
