---
# tasks file for openvpn

- name: Create Server dirs and links
  file:
    path: "~/{{ item }}"
    state: directory
  loop:
    - "{{ CERT_ROOT_DIR }}"

- name: Get Server template
  template:
    src: "{{ item.name }}.j2" 
    dest: "{{ item.path }}"
  loop:
    - { name: "server.conf", path: "/etc/openvpn/server.conf" }
    - { name: "vars", path: "~/{{ CERT_ROOT_DIR }}/vars"}

- name: Build PKI
  command: "/usr/share/easy-rsa/easyrsa init-pki"
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: "Build CA"
  become: yes
  shell: >
    yes "" | /usr/share/easy-rsa/easyrsa build-ca nopass;
  args: 
    chdir: "~/{{ CERT_ROOT_DIR }}"
    executable: /bin/bash

- name: Build DH
  command: "/usr/share/easy-rsa/easyrsa gen-dh"
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Build PEM key
  command: "/usr/share/easy-rsa/easyrsa gen-crl"
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Build TA
  command: "openvpn --genkey --secret ta.key"
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Build certificate server
  command: "/usr/share/easy-rsa/easyrsa build-server-full server nopass"
  args:
    chdir: "~/{{ CERT_ROOT_DIR }}"

- name: Copy server.key, server.crt, ca.crt, dh.pem, ta.key
  copy:
    src: "~/{{ CERT_ROOT_DIR }}/{{ item.path }}/{{ item.name }}"
    dest: "/etc/openvpn/{{ item.name }}"
    remote_src: yes  
  loop:
    - { name: "server.crt", path: "pki/issued"}
    - { name: "server.key", path: "pki/private"}
    - { name: "ca.crt", path: "pki"}
    - { name: "crl.pem", path: "pki"}
    - { name: "dh.pem", path: "pki"}
    - { name: "ta.key", path: "."}
